# Generated by Django 4.0.2 on 2023-02-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='giosg_visitor_global_id',
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='giosg_chat_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
